### ISSUE TITLE
Add support for ES384 and ES512 algorithms

### ISSUE THREAD

**Issue by tjmullicani** [glatzert/ACME-Server-ADCS#12]
Add support for ES384 and ES512 algorithms.

https://github.com/glatzert/ACME-Server-ADCS/blob/32b81e505f782409bf5c4c6785a4cb209417283d/src/ACME.Protocol/RequestServices/DefaultRequestValidationService.cs#L22

https://www.rfc-editor.org/rfc/rfc7518#section-3.1

**Comment by glatzert** [comment]
Hi Timothy,
I'll integrate your PR, but keep this issue open, to remind me of moving the collection in the configuration file.
