### ISSUE TITLE
Subject empty

### ISSUE THREAD

**Issue by sedstr** [glatzert/ACME-Server-ADCS#16]
Firstly thanks for making this tool available, awesome work!

I've followed the installation instructions and I'm able to request a working SSL certificate from an MS CA, but even though the certificate appears as valid, the subject value is empty while the subject alternative name is populated. I'm trying to populate both values with the same hostname.

I've tried different value combinations at the json config level and tried passing multiple values through certbot without success - it either fails or works but is still missing the subject value.

I'm sure this is a simple problem that I shouldn't need to ask for assistance on, but if you could spare a moment to share your knowledge, I'd really appreciate it.

**Comment by glatzert** [comment]
That's _probably_ on your client. The server does not meddle with the CSR - it will validate the DNS SANs and CN, but not change it.

**Comment by vestaxbham** [comment]
I'd like to thank you too. That's exactly what I've been looking for.

I have the same issue as @sedstr mentioned. I have tried different versions of certbot (from 1.27 till latest 2.6.0). The enrollment of the certificate works like a charm, but each has an empty subject. 
When I set 'AllowEmptyCN' to 'false' this error occurs when I try to enroll a certificate:

 "error":{"type":"urn:ietf:params:acme:error:badCSR","detail":"CN Invalid."}

I am using the Windows variant of certbot. Maybe this could be the reason? Any ideas?

Thanks again!

**Comment by glatzert** [comment]
Without exposing private data, are you able to provide the CSR?

**Comment by glatzert** [comment]
Also on a side note - why do you need the subject to be present?

**Comment by vestaxbham** [comment]
Thanks for your response.
This is the CSR decoded:

`openssl req -text -in c:\temp\cert\Request\csr.csr
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject:
        Subject Public Key Info:

Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:server01.server.srv,server01
`

As you can see, subject field is empty, but SAN is filled correctly. 

I have some applications for those I do need the subject, e.g. for network authentication. If the CN is empty the client cannot verify the certificate and the authentication fails.

From my point of you the CN is missing in the CSR, so I guess I cannot resolve this issue on the Windows CA-side?!

**Comment by glatzert** [comment]
I'm no expert in templates, but there are probably some settings around the subject name as well.

**Comment by glatzert** [comment]
Also - if certbot does not allow you to set the CN (which is okay, since it's all build for browsers and web-servers), you might just use another client.
