### ISSUE TITLE
Some proposals for the README

### ISSUE THREAD

**Issue by christophvw** [glatzert/ACME-Server-ADCS#23]
Some proposals for the README

> or you want a maintenance contract, feel free to contact me and we most likely will find a way.

you should add a contact here (mail?)

>Grant full rights to the account used above

Why full permissions? Read/Write is not enough?

>"Modify the IIS-AppPool, to not use .NET Framework (new .NET is loaded via another mechanism) and set it's identity to either a custom account (recommended) or "NetworkService"."

The recommended account type should be a managed service account.
And any type of custom account will need the permission "Log on as a batch job"

**Comment by glatzert** [comment]
Thank you for you suggestions - I included them in the current release.
