### ISSUE TITLE
Works with Autoenroll?

### ISSUE THREAD

**Issue by NowyQuei** [glatzert/ACME-Server-ADCS#27]
Hi
I've successfully installed everything as per the instructions and it was initially working fine until I encountered a minor issue which necessitated the installation of .NET 6. This might be an important detail worth mentioning in the installation guide.

For my test, I aim to ensure that any server joining the domain or already a domain member automatically receives a certificate from ADCS via the ACME server. My configuration follows the guidelines provided, including a supplementary guide from StarWind Software on server certificate auto-enrollment (https://www.starwindsoftware.com/blog/server-certificate-auto-enrollment).

However, I suspect the problem might be because I've only installed the ADCS-Cert-Authority role without the ADCS-Enroll-* roles. Is it possible to integrate autoenrollment with this ACME project, and if so, how can it be achieved?

**Comment by glatzert** [comment]
Hi,

can you elaborate the use case behind that?
ACME is already an automatable process to renew certificates and I think auto-enroll somewhat does the same?
