### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by heymex** [glatzert/ACME-Server-ADCS#29]
Is this license attached to the project legitimate?  Even for an educational institution, it barely makes sense.  At least in the US, colleges charge fees per credit, not semester, so the fees will fluctuate wildly depending on courseload.

**Comment by glatzert** [comment]
It's intentionally written to exclude education providers taking more than some "adminsitration fee". If you like I can be more precise with that in the licence, by specifically excluding "pay per credit" from the free licence.
