### ISSUE TITLE
[HTTP] Request completed with status NotFound

### ISSUE THREAD

**Issue by panamaus** [glatzert/ACME-Server-ADCS#41]
I successfully installed version 2.0.2 and was able to enroll for a certificate using win-acme, so first off thanks for developing this solution! It's the only one I've found that isn't embedded as optional functionality in some larger commercial product, or that functions as a proxy to some dependency service like CAWE.

My question isn't so much with functionality as it is with presentation. When the ACME client (win-acme) connects to the service, the response is "[HTTP] Request completed with status NotFound". It recurs during the enrollment process. This error-looking response doesn't happen when connecting to Let's Encrypt. What's causing this and how can I make it stop? I'd rather not have to answer a hundred questions from people in my enterprise as to what this means.

**Comment by glatzert** [comment]
I've not tested it with win-acme, yet. But, I'll can do next Werk.
Could be interesting to see the logs of the acme server, though - could you provide them?

**Comment by glatzert** [comment]
I was able to take a look into the issue with WACS. Assume your ACME-Server name be "acme.th11s.corp". If you put that into the WACS settings (e.g. https://acme.th11s.corp), it'll try to read https://acme.th11s.corp/directory, which does not exist. Then it'll fallback to https://acme.th11s.corp/, which exists.
I could hide the problem, by allowing both urls, but essentially it's a flaw in WACS.

.. I'll build a patch, allowing both paths ..
